Repository d702e20/CGAAL, pull requests merged in 2023-10, with the labels that each got.

#230 Add random DFS search strategy
  benches/benchmark_solver.rs
  cgaal-cli/Cargo.toml
  cgaal-cli/src/args.rs
  cgaal-cli/src/options.rs
  cgaal-cli/src/solver.rs
  cgaal-engine/Cargo.toml
  cgaal-engine/src/algorithms/certain_zero/search_strategy/mod.rs
  cgaal-engine/src/algorithms/certain_zero/search_strategy/rdfs.rs
Labels: hacktoberfest-accepted

#231 Add paper to README
  README.md
Labels: documentation, hacktoberfest-accepted

#232 Use new AST for LCGS and give better errors
  benches/benchmark_solver.rs
  cgaal-cli/Cargo.toml
  cgaal-cli/src/load.rs
  cgaal-cli/src/main.rs
  cgaal-engine/Cargo.toml
  cgaal-engine/src/algorithms/certain_zero/search_strategy/instability_heuristic_search.rs
  cgaal-engine/src/algorithms/certain_zero/search_strategy/linear_constrained_phi.rs
  cgaal-engine/src/algorithms/certain_zero/search_strategy/linear_constraints.rs
  cgaal-engine/src/algorithms/certain_zero/search_strategy/linear_optimize.rs
  cgaal-engine/src/algorithms/certain_zero/search_strategy/linear_programming_search.rs
  cgaal-engine/src/algorithms/certain_zero/search_strategy/linear_representative_search.rs
  cgaal-engine/src/algorithms/game_strategy/partial.rs
  cgaal-engine/src/atl/convert.rs
  cgaal-engine/src/atl/mod.rs
  cgaal-engine/src/edg/atledg/format.rs
  cgaal-engine/src/edg/atledg/mod.rs
  cgaal-engine/src/edg/atledg/pmoves.rs
  cgaal-engine/src/edg/atledg/vertex.rs
  cgaal-engine/src/game_structure/eager.rs
  cgaal-engine/src/game_structure/lcgs/ast.rs
  cgaal-engine/src/game_structure/lcgs/eval.rs
  cgaal-engine/src/game_structure/lcgs/intermediate.rs
  cgaal-engine/src/game_structure/lcgs/ir/error.rs
  cgaal-engine/src/game_structure/lcgs/ir/eval.rs
  cgaal-engine/src/game_structure/lcgs/ir/intermediate.rs
  cgaal-engine/src/game_structure/lcgs/ir/mod.rs
  cgaal-engine/src/game_structure/lcgs/ir/relabeling.rs
  cgaal-engine/src/game_structure/lcgs/ir/symbol_checker.rs
  cgaal-engine/src/game_structure/lcgs/ir/symbol_table.rs
  cgaal-engine/src/game_structure/lcgs/mod.rs
  cgaal-engine/src/game_structure/lcgs/parse.rs
  cgaal-engine/src/game_structure/lcgs/precedence.rs
  cgaal-engine/src/game_structure/lcgs/query.rs
  cgaal-engine/src/game_structure/lcgs/relabeling.rs
  cgaal-engine/src/game_structure/lcgs/symbol_checker.rs
  cgaal-engine/src/game_structure/lcgs/symbol_table.rs
  cgaal-engine/src/game_structure/mod.rs
  cgaal-engine/src/parsing/ast.rs
  cgaal-engine/src/parsing/errors.rs
  cgaal-engine/src/parsing/lexer.rs
  cgaal-engine/src/parsing/mod.rs
  cgaal-engine/src/parsing/parser.rs
  cgaal-engine/src/parsing/span.rs
  cgaal-engine/tests/parsing_expr.rs
  cgaal-engine/tests/parsing_lcgs.rs
  cgaal-engine/tests/partial_strategy_synthesis.rs
  test.atl
  test.lcgs
Labels: enhancement, refactoring
